/* Catalogue de démonstration — L'Atelier de Meliah */
const PRODUCTS = [
  {
    id: "sac-a-langer-lin",
    name: "Sac à langer en lin lavé",
    category: "Naissance",
    price: 89,
    oldPrice: null,
    rating: 5,
    reviews: 34,
    badge: "Best-seller",
    img: "https://images.unsplash.com/photo-1583710457367-47de0ea21fef?auto=format&fit=crop&w=800&q=80",
    imgHover: "https://images.unsplash.com/photo-1552819289-e14fbbcea868?auto=format&fit=crop&w=800&q=80",
    personalisable: true,
    desc: "Confectionné à la main dans un lin lavé français, ce sac à langer accompagne bébé dès les premiers jours. Doublure imperméable, matelas à langer assorti offert."
  },
  {
    id: "attache-tetine-gaze",
    name: "Attache-tétine en gaze de coton",
    category: "Éveil",
    price: 19,
    oldPrice: 24,
    rating: 5,
    reviews: 58,
    badge: null,
    img: "https://images.unsplash.com/photo-1644611421265-e0b85a3e3f11?auto=format&fit=crop&w=800&q=80",
    imgHover: "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?auto=format&fit=crop&w=800&q=80",
    personalisable: true,
    desc: "Douce gaze de coton certifiée Oeko-Tex, brodée au prénom de votre choix. Attache sécurisée compatible avec toutes les tétines standards."
  },
  {
    id: "anneau-dentition-bois",
    name: "Anneau de dentition en bois brut",
    category: "Éveil",
    price: 16,
    oldPrice: null,
    rating: 4,
    reviews: 21,
    badge: "Nouveau",
    img: "https://images.unsplash.com/photo-1644611421265-e0b85a3e3f11?auto=format&fit=crop&w=800&q=80&sat=-10",
    imgHover: "https://images.unsplash.com/photo-1739117441029-9f2a8e59e8b2?auto=format&fit=crop&w=800&q=80",
    personalisable: false,
    desc: "Sculpté dans un bois de hêtre local et fini à l'huile alimentaire, cet anneau accompagne en douceur la poussée dentaire."
  },
  {
    id: "protege-carnet-sante",
    name: "Protège carnet de santé lin & liberty",
    category: "Naissance",
    price: 24,
    oldPrice: null,
    rating: 5,
    reviews: 45,
    badge: null,
    img: "https://images.unsplash.com/photo-1705290304455-35ffb433f560?auto=format&fit=crop&w=800&q=80",
    imgHover: "https://images.unsplash.com/photo-1707914703104-b70cddf191cb?auto=format&fit=crop&w=800&q=80",
    personalisable: true,
    desc: "Un protège-carnet cousu main qui protège précieusement les premiers documents de bébé, personnalisable au prénom."
  },
  {
    id: "bavoir-double-gaze",
    name: "Bavoir double gaze de coton",
    category: "Repas",
    price: 18,
    oldPrice: null,
    rating: 5,
    reviews: 39,
    badge: null,
    img: "https://images.unsplash.com/photo-1552819289-e14fbbcea868?auto=format&fit=crop&w=800&q=80&sat=-10",
    imgHover: "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?auto=format&fit=crop&w=800&q=80&sat=-10",
    personalisable: true,
    desc: "Absorbant et ultra doux pour la peau de bébé, ce bavoir en double gaze de coton résiste à un usage quotidien intensif."
  },
  {
    id: "lingettes-lavables-x10",
    name: "Lot de 10 lingettes lavables",
    category: "Repas",
    price: 22,
    oldPrice: null,
    rating: 4,
    reviews: 27,
    badge: "Éco-responsable",
    img: "https://images.unsplash.com/photo-1705290304455-35ffb433f560?auto=format&fit=crop&w=800&q=80&sat=-15",
    imgHover: "https://images.unsplash.com/photo-1640767760729-7bfb6ce43ad4?auto=format&fit=crop&w=800&q=80",
    personalisable: false,
    desc: "Coton biologique certifié GOTS, un geste doux pour la peau de bébé et pour la planète. Lavables en machine à 60°."
  },
  {
    id: "doudou-lapin-lin",
    name: "Doudou lapin en lin brodé",
    category: "Éveil",
    price: 34,
    oldPrice: null,
    rating: 5,
    reviews: 62,
    badge: "Coup de cœur",
    img: "https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=800&q=80",
    imgHover: "https://images.unsplash.com/photo-1644611421265-e0b85a3e3f11?auto=format&fit=crop&w=800&q=80",
    personalisable: true,
    desc: "Le compagnon des premières nuits, cousu à la main en lin et coton biologique, brodé au prénom de bébé."
  },
  {
    id: "coffret-naissance-essentiel",
    name: "Coffret naissance « Essentiel »",
    category: "Naissance",
    price: 129,
    oldPrice: 149,
    rating: 5,
    reviews: 18,
    badge: "Édition limitée",
    img: "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?auto=format&fit=crop&w=800&q=80&sat=10",
    imgHover: "https://images.unsplash.com/photo-1583710457367-47de0ea21fef?auto=format&fit=crop&w=800&q=80&sat=10",
    personalisable: true,
    desc: "Sac à langer, attache-tétine, protège-carnet et bavoir assortis dans un écrin en coton — le cadeau de naissance parfait."
  },
  {
    id: "guirlande-prenom-bois",
    name: "Guirlande prénom en bois",
    category: "Décoration",
    price: 42,
    oldPrice: null,
    rating: 5,
    reviews: 15,
    badge: null,
    img: "https://images.unsplash.com/photo-1640767760729-7bfb6ce43ad4?auto=format&fit=crop&w=800&q=80",
    imgHover: "https://images.unsplash.com/photo-1707914703104-b70cddf191cb?auto=format&fit=crop&w=800&q=80",
    personalisable: true,
    desc: "Chaque lettre est découpée et peinte à la main pour composer une guirlande unique au prénom de votre enfant."
  },
  {
    id: "housse-poussette-gaze",
    name: "Housse de poussette en gaze",
    category: "Décoration",
    price: 39,
    oldPrice: null,
    rating: 4,
    reviews: 11,
    badge: null,
    img: "https://images.unsplash.com/photo-1705290304455-35ffb433f560?auto=format&fit=crop&w=800&q=80&sat=5",
    imgHover: "https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=800&q=80&sat=10",
    personalisable: false,
    desc: "Légère et respirante, cette housse protège bébé du soleil et des regards tout en habillant la poussette avec élégance."
  },
  {
    id: "couverture-nid-ange",
    name: "Couverture nid d'ange en laine",
    category: "Naissance",
    price: 68,
    oldPrice: null,
    rating: 5,
    reviews: 29,
    badge: null,
    img: "https://images.unsplash.com/photo-1552819289-e14fbbcea868?auto=format&fit=crop&w=800&q=80&sat=10",
    imgHover: "https://images.unsplash.com/photo-1583710457367-47de0ea21fef?auto=format&fit=crop&w=800&q=80&sat=10",
    personalisable: true,
    desc: "Chaude et enveloppante, cette couverture en laine mérinos et coton biologique berce bébé dans un cocon de douceur."
  },
  {
    id: "carnet-naissance-brode",
    name: "Carnet de naissance brodé",
    category: "Décoration",
    price: 28,
    oldPrice: null,
    rating: 5,
    reviews: 9,
    badge: "Nouveau",
    img: "https://images.unsplash.com/photo-1707914703104-b70cddf191cb?auto=format&fit=crop&w=800&q=80&sat=-10",
    imgHover: "https://images.unsplash.com/photo-1640767760729-7bfb6ce43ad4?auto=format&fit=crop&w=800&q=80&sat=-10",
    personalisable: true,
    desc: "Un carnet relié à la main pour consigner les premiers souvenirs, la couverture en lin brodée au prénom de bébé."
  }
];

const COLLECTIONS = [
  { key: "Naissance", title: "Naissance", desc: "Sacs à langer, coffrets et couvertures pour accueillir bébé", img: "https://images.unsplash.com/photo-1552819289-e14fbbcea868?auto=format&fit=crop&w=900&q=80" },
  { key: "Repas", title: "Repas", desc: "Bavoirs et lingettes en coton biologique", img: "https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=700&q=80" },
  { key: "Éveil", title: "Éveil", desc: "Doudous, attaches-tétines et anneaux de dentition", img: "https://images.unsplash.com/photo-1644611421265-e0b85a3e3f11?auto=format&fit=crop&w=700&q=80" },
  { key: "Personnalisation", title: "Personnalisation", desc: "Composez une création unique brodée au prénom", img: "https://images.unsplash.com/photo-1705290304455-35ffb433f560?auto=format&fit=crop&w=700&q=80" },
  { key: "Décoration", title: "Décoration", desc: "Guirlandes, carnets et objets pour la chambre de bébé", img: "https://images.unsplash.com/photo-1640767760729-7bfb6ce43ad4?auto=format&fit=crop&w=700&q=80" }
];

function findProduct(id){ return PRODUCTS.find(p => p.id === id); }
